Add function to remove a local branch
jasonmccreary/git-trim pull request #4
Opened 2022-02-13 15:05 UTC by mohammed-elhaouari

## Description

Inspired by Laravel `php artisan migrate --pretend`, that prints SQL queries instead of running them on the database. 

I have added a new flag `--dry-run` to `git trim`, that prints branches going to be trimmed instead of actually deleting them.

This will solve the problem of not knowing what branches are going to be impacted, fearing to delete unwanted branches.

### Changes

- Added `--dry-run` flag to `git trim` option.
- Added `remove_local_branch` function.
- Sorted flags by alphabetical order.

2022-02-13 15:06 UTC, mhdcodes commented
@jasonmccreary This pr has both changes. Adding the flag `dry` and creating a function for deleting branches. 

Let me know if I should add the changes here to my previous pr.

2022-02-13 15:08 UTC, jasonmccreary commented
@mohammed-elhaouari, thanks. I'll clean this up shortly as I just pushed some changes to `master`.

2022-02-13 15:10 UTC, mohammed-elhaouari commented
@jasonmccreary great. Good luck mate.

2022-02-13 16:28 UTC, jasonmccreary commented
I'm working on one more change in `main`, then I'll resolve these conflicts and get this merged.

2022-02-13 16:40 UTC, mohammed-elhaouari commented
@jasonmccreary I have resolved old merge conflicts. Left for you to do the cleanup.

2022-02-13 16:51 UTC, jasonmccreary commented
Again, I have more changes inbound. However, if you're going to work on it, please make the option `dry-run` inline with other common commands.

2022-02-13 20:40 UTC, jasonmccreary requested changes
I'm done making changes on `main`, but noticed a few additional this would need before merging. Could you please give it another pass for my comments as well as conflicts when you get a minute. 👍

2022-02-13 20:40 UTC, jasonmccreary commented on git-trim
> +dry-run!          prints branches to output instead of deleting theme
Add in alphabetical order.

2022-02-13 20:40 UTC, jasonmccreary commented on git-trim
> +    echo "${branch} will be trimmed."
Use `$1` for argument to avoid global variable reference.

2022-02-13 20:40 UTC, jasonmccreary commented on git-trim
> +  git push -d $1 $2 > /dev/null 2>&1
Would need `dry-run` here too.

2022-02-13 21:30 UTC, mohammed-elhaouari commented
@jasonmccreary I have resolved all conflicts. And resolved the points raised. I have also sorted flags in alphabetical order. Though,  I think `dry-run` and `reset` flags should be the last options. When you run `git trim -h` it makes sense to see them last in the last, it gives visual feedback that these 2 options are secondary options.

I don't know, but I feel that flags should not be sorted alphabetically

2022-02-13 21:32 UTC, mohammed-elhaouari commented
![image](https://user-images.githubusercontent.com/9967336/153775918-746b7c8d-36fc-4edf-86ce-c220faa48f45.png)

Vs

![image](https://user-images.githubusercontent.com/9967336/153775933-ef67a75d-510a-4a1d-836e-8f523a6bbaa7.png)

2022-02-13 21:38 UTC, jasonmccreary commented
@mohammed-elhaouari, let's keep it alphabetical.

Also, please do not make formatting changes to the code.

2022-02-13 22:00 UTC, mohammed-elhaouari commented
@jasonmccreary removed all the automatic formatting applied by my IDE.

2022-02-14 12:06 UTC, jasonmccreary commented on git-trim
> -      git branch -d $branch
Probably not a big deal, but this was using `-d` before, and now it's `-D`.

2022-02-14 12:06 UTC, jasonmccreary commented
@mohammed-elhaouari, awesome. Thanks for your continued work on this!

2022-02-14 12:06 UTC, merged

2022-02-14 12:20 UTC, mhdcodes commented
@jasonmccreary always a pleasure.